// scripts/generate-sitemap.mjs
//
// Writes public/sitemap.xml from the routes and blog content that exist at
// build time.
//
// Generated rather than hand-maintained because a hand-written sitemap goes
// stale the first time someone adds a post and forgets, and a sitemap listing
// URLs that 404 is worse than having none.
//
// Only content known at build time is included. User-generated pages — forum
// threads, groups, public profiles — are dynamic and belong in a sitemap served
// by the API, since only it knows what exists. That is noted below rather than
// silently omitted.
//
// Run: node scripts/generate-sitemap.mjs   (wired into `pnpm build`)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

const SITE = (process.env.VITE_SITE_URL || 'https://panelist.app').replace(/\/$/, '');

/** Static, indexable routes. Anything behind auth is deliberately absent. */
const STATIC_ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/blog', changefreq: 'daily', priority: '0.8' },
  { path: '/forum', changefreq: 'daily', priority: '0.7' },
  { path: '/groups', changefreq: 'weekly', priority: '0.6' },
];

/**
 * Pull slugs and dates straight from the blog source, so adding a post updates
 * the sitemap with no extra step. Parsed with a regex rather than imported
 * because the source is TypeScript and this runs as plain Node.
 */
function readBlogPosts() {
  const file = join(root, 'src/data/blog-posts.ts');
  let source;
  try {
    source = readFileSync(file, 'utf8');
  } catch {
    console.warn('[sitemap] blog-posts.ts not found — skipping blog URLs');
    return [];
  }

  const posts = [];
  const slugRe = /slug:\s*'([^']+)'/g;
  const dateRe = /publishedAt:\s*'([^']+)'/g;

  const slugs = [...source.matchAll(slugRe)].map((m) => m[1]);
  const dates = [...source.matchAll(dateRe)].map((m) => m[1]);

  slugs.forEach((slug, i) => {
    posts.push({ slug, lastmod: dates[i] ?? null });
  });

  return posts;
}

function urlEntry({ path, lastmod, changefreq, priority }) {
  return [
    '  <url>',
    `    <loc>${SITE}${path}</loc>`,
    lastmod ? `    <lastmod>${lastmod.slice(0, 10)}</lastmod>` : null,
    changefreq ? `    <changefreq>${changefreq}</changefreq>` : null,
    priority ? `    <priority>${priority}</priority>` : null,
    '  </url>',
  ]
    .filter(Boolean)
    .join('\n');
}

const posts = readBlogPosts();

const entries = [
  ...STATIC_ROUTES.map(urlEntry),
  ...posts.map((p) =>
    urlEntry({
      path: `/blog/${p.slug}`,
      lastmod: p.lastmod,
      changefreq: 'monthly',
      priority: '0.7',
    }),
  ),
];

const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by scripts/generate-sitemap.mjs — do not edit by hand.
     Dynamic content (forum threads, groups, public profiles) is not listed
     here; only the API knows what exists, so those belong in a sitemap it
     serves. -->
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${entries.join('\n')}
</urlset>
`;

writeFileSync(join(root, 'public/sitemap.xml'), xml, 'utf8');
console.log(
  `[sitemap] wrote ${entries.length} URLs (${STATIC_ROUTES.length} static, ${posts.length} blog) → public/sitemap.xml`,
);
